### ISSUE TITLE
Conference Paper: Sim-MPPS by MLPro - A Versatile and Configurable Production System Simulator in Python

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-MPPS#15]
**Description/Motivation**

 Title Proposal:
  - [ ]  Sim-MPPS by MLPro - A Versatile and Customizable Production System Simulator in Python
  - [ ]  Sim-MPPS by MLPro - A Versatile and Configurable Production System Simulator in Python
  - [ ]  Sim-MPPS by MLPro - A Customizable Multi-Purpose Production System Simulation in Python

Submission Target:
  - [ ] ETFA 2023 - https://2023.ieee-etfa.org/ (Deadline: 31st March 2023) - Free of charge up to 8 pages
  - [ ] IECON 2023 - https://www.iecon2023.org/ (Deadline: 30th April 2023) - Free of charge up to 6 pages
  

**Task list**
- [ ] 1. Do this
- [ ] 2. Do that

**Related issues**
#...

**Cross references**
...
