### ISSUE TITLE
HowTos: Setup Component, Module, MPPS

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-MPPS#19]
**Description/Motivation**
...

**Task list**
- [ ] How to setup a component
- [ ] How to setup a module
- [ ] How to setup mpps (setup_mpps function)

**Related issues**
#...

**Cross references**
...
