### ISSUE TITLE
MPPS Meeting on 27.02.2023

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-MPPS#34]
**Description/Motivation**

Discussion Topics:

- [ ] Actual status of Sim-MPPS, including howtos, new features, licensing, documentation, simulation results, etc. (Steve)
- [ ] Validation of Sim-MPPS #17 (Steve/Marlon)
- [ ] New Environment for EA and Supervised Learning #21 (Marlon)
- [ ] Assign the remaining unassigned issues (Steve/Marlon)
- [ ] Papers (Steve/Marlon):
  - [ ] Conference Paper in EFTA or IECON #15
  - [ ] Short Paper in Software Impact Journal #33
