### ISSUE TITLE
Add Experiment Findings in Research Gate

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-MPPS#36]
**Description/Motivation**
Add experiment findings of Sim-MPPS in Research Gate (https://www.researchgate.net/project/MLPro-A-Synoptic-Framework-for-Standardized-Machine-Learning-Tasks-in-Python). Also additionally, add the finding of ABB robots.

**Task list**
- [ ] BGLP on Sim-MPPS (A2C, PPO, SbPG)
- [ ] New Environment on Sim-MPPS (EA)
- [ ] New Environment on Sim-MPPS (SL?)
- [x] RL on ABB Robots

**Related issues**
#...

**Cross references**
...
